---
- hosts: 172.31.95.33
  become: yes
  become_method: sudo
  remote_user: ubuntu
  tasks:
  - name: Copy WAR file to target host
    copy:
      src: /home/ubuntu/war/sample.war
      dest: /opt/tomcat/webapps/sample.war
  - name: Deploy WAR file to Tomcat
    shell: /opt/tomcat/bin/startup.sh sample.war
